services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:hive
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - "443:443"
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:hive
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    secrets: [mysql_pass, wp_admin_pass, wp_pass]
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:hive
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    secrets:
      [mysql_root_pass, mysql_pass]
  redis:
    container_name: redis
    build: ./bonus/redis
    image: redis:hive
    restart: always
    networks:
      - inception
  ftp:
    container_name: ftp
    build: ./bonus/ftp
    image: ftp:hive
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    secrets: [ftp_pass]
  adminer:
    container_name: adminer
    build: ./bonus/adminer
    image: adminer:hive
    restart: always
    networks:
      - inception
  static:
    container_name: static
    build: ./bonus/static
    image: static:hive
    restart: always
    networks:
      - inception
  netdata:
    container_name: netdata
    build: ./bonus/netdata
    image: netdata:hive
    restart: always
    networks:
      - inception
    volumes:                    # read-only host data Netdata needs
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
networks:
  inception:
    driver: bridge
secrets:
  mysql_root_pass:  {file: ../secrets/mysql_root_pass}
  mysql_pass:       {file: ../secrets/mysql_pass}
  wp_admin_pass:    {file: ../secrets/wp_admin_pass}
  wp_pass:          {file: ../secrets/wp_pass}
  ftp_pass:         {file: ../secrets/ftp_pass}
