services:
  nginx:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    restart: always
    env_file:
      - .env
    networks:
      inception:
        ipv4_address: 192.168.42.42
  wordpress:
    build: ./wordpress
    networks:
      inception:
        ipv4_address: 192.168.42.43
  mariadb:
    build: ./mariadb
    # volumes:
    #   - mariadb_data:/var/lib/mysql
    ports:
      - "4444:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=a
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=wppassword
    networks:
      inception:
        ipv4_address: 192.168.42.44
# volumes:
#   mariadb_data:
networks:
  inception:
    driver: bridge
    ipam:
      config:
      - subnet: "192.168.42.0/24"
