services:
  nginx:
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      inception:
        ipv4_address: 192.168.42.42
  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      inception:
        ipv4_address: 192.168.42.43
  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      inception:
        ipv4_address: 192.168.42.44
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
networks:
  inception:
    driver: bridge
    ipam:
      config:
      - subnet: "192.168.42.0/24"
