services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:hive
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:hive
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:hive
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
  redis:
    container_name: redis
    build: ./bonus/redis
    image: redis:hive
    restart: always
    networks:
      - inception
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
networks:
  inception:
    driver: bridge
