#!/bin/sh
set -euo pipefail

echo "─── MariaDB ─────────────────────────────"
read -s -p "Root password                 : " MYSQL_ROOT_PASS;  echo
read -r -p "Database name     [wordpress] : " MYSQL_DATABASE
MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
read -r -p "App DB user        [aklein]  : " MYSQL_USER
MYSQL_USER=${MYSQL_USER:-aklein}
read -s -p "App DB user password          : " MYSQL_PASS;       echo

echo
echo "─── WordPress ───────────────────────────"
read -r -p "Site title        [Inception]: " WP_TITLE
WP_TITLE=${WP_TITLE:-Inception}
read -r -p "Admin user           [root]  : " WP_ADMIN
WP_ADMIN=${WP_ADMIN:-root}
read -s -p "Admin password                : " WP_ADMIN_PASS;     echo
read -r -p "Admin e-mail   [root@admin.com]: " WP_ADMIN_MAIL
WP_ADMIN_MAIL=${WP_ADMIN_MAIL:-root@admin.com}

read -r -p "Regular user       [${MYSQL_USER}] : " WP_USER
WP_USER=${WP_USER:-$MYSQL_USER}
read -s -p "Regular user password          : " WP_PASS;          echo
read -r -p "Regular user e-mail [a@gmail.com]: " WP_MAIL
WP_MAIL=${WP_MAIL:-a@gmail.com}

echo
echo "─── FTP ─────────────────────────────────"
read -r -p "FTP user            [ftpuser]: " FTP_USER
FTP_USER=${FTP_USER:-ftpuser}
read -s -p "FTP user password               : " FTP_PASS;        echo
echo "─────────────────────────────────────────"

# ------------------------------------------------------------------
# 1.  Write the secret files
# ------------------------------------------------------------------
rm -rf secrets
mkdir -p secrets
printf '%s' "$MYSQL_ROOT_PASS"  > secrets/mysql_root_pass
printf '%s' "$MYSQL_PASS"  > secrets/mysql_pass
printf '%s' "$WP_ADMIN_PASS"    > secrets/wp_admin_pass
printf '%s' "$WP_PASS"     > secrets/wp_pass
printf '%s' "$FTP_PASS"         > secrets/ftp_pass
chmod 400 secrets/*

# ------------------------------------------------------------------
# 2.  Write the public / tweakable variables to .env
# ------------------------------------------------------------------
cat > .env <<EOF
# ─── generated by bootstrap.sh ───
SERVER_NAME=aklein.42.fr

SSL_CERT_DIR=/etc/nginx/certs
SSL_CRT=/etc/nginx/certs/server.crt
SSL_KEY=/etc/nginx/certs/server.key

# ------------ MariaDB ------------
MYSQL_DATABASE=$MYSQL_DATABASE
MYSQL_USER=$MYSQL_USER

# ----------- WordPress -----------
WP_PATH=/var/www/html
WP_TITLE=$WP_TITLE
WP_USER=$WP_USER
WP_MAIL=$WP_MAIL
WP_ADMIN=$WP_ADMIN
WP_ADMIN_MAIL=$WP_ADMIN_MAIL

# -------------- FTP --------------
FTP_USER=$FTP_USER
EOF

echo "✅  Secret files written to  .srcs/secrets/   (chmod 400)"
echo "✅  Public vars written to  .env"
